spring:
  application:
    name: fsc

  server:
    address: 0.0.0.0
    port: 8080

  profiles:
    active: local

  aws:
    dynamodb:
      endpoint: https://dynamodb.us-east-2.amazonaws.com
      accessKeyId: ${accessKeyId}
      secretAccessKey: ${secretAccessKey}
      region: us-east-2

logging:
  level:
    root: INFO
    com.yonasamare.fsc: DEBUG

dictionary:
  api:
    url: https://www.dictionaryapi.com/api/v3/references/sd2/json
    key: 6a9d495c-bc16-4e9b-946a-06bbf9d13d55

